export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const ADD_CLASS_FILTER = 'ADD_CLASS_FILTER';
export const ADD_SUBJECT_FILTER = 'ADD_SUBJECT_FILTER';
export const REMOVE_CLASS_FILTER = 'REMOVE_CLASS_FILTER';
export const REMOVE_SUBJECT_FILTER = 'REMOVE_SUBJECT_FILTER';